- .github/workflows/backend.yml
> [chore] Github action CI 백엔드 스크립트를 등록한다.

- .github/workflows/backend-ci-cd.yml
- appspec.yml
> [chore] codedeploy 배포 관련 파일 수정

- appspec.yml
- build.gradle
- execute-deploy.sh
- src/main/java/com/backend/arthere/ArtHereApplication.java
- src/main/java/com/backend/arthere/global/WebRestController.java
- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
서버 배포 환경 구축
- 외부 파일을 실행하도록 경로를 작성해 ArtHereApplication 로컬에서 사용 주의
- Application을 새로 만들어 사용하는것을 추천합니다.
> [chore] 서버 배포 환경 구축한다.

- .github/workflows/backend-ci-cd.yml
- src/main/java/com/backend/arthere/global/config/JasyptConfig.java
- src/main/resources/application.yml
> [feat] jasypt 암호화 키 환경변수 설정

- build.gradle
- src/main/java/com/backend/arthere/auth/application/CustomUserDetailsService.java
- src/main/java/com/backend/arthere/auth/domain/Token.java
- src/main/java/com/backend/arthere/auth/domain/TokenRepository.java
- src/main/java/com/backend/arthere/auth/domain/UserPrincipal.java
- src/main/java/com/backend/arthere/auth/exception/FailedTokenAuthenticationException.java
- src/main/java/com/backend/arthere/auth/jwt/JwtAccessDeniedHandler.java
- src/main/java/com/backend/arthere/auth/jwt/JwtAuthenticationEntryPoint.java
- src/main/java/com/backend/arthere/auth/jwt/JwtTokenAuthenticationFilter.java
- src/main/java/com/backend/arthere/auth/jwt/JwtTokenProvider.java
- src/main/java/com/backend/arthere/global/config/JasyptConfig.java
- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
jwt 액세스 토큰, 리프레시 토큰을 생성한다.
리프레시 토큰은 db에 저장한다. 
사용자 인증과정을 진행할 때 db에 사용자의 리프레시 토큰이 있는지 확인하는 과정을 거쳤습니다. (로그아웃 기능을 위한)
jwt 코드를 어떤 패키지에 넣어야할지 고민하다가 따로 jwt 패키지를 생성했습니다!
jasypt 관련해서 환경변수 변경했습니다.. 환경변수 관련해서 삽질좀 해서 commit이 조금 많아요..
> [feat] jwt를 구현한다.

- build.gradle
- src/main/java/com/backend/arthere/auth/application/AuthService.java
- src/main/java/com/backend/arthere/auth/application/CustomOAuth2UserService.java
- src/main/java/com/backend/arthere/auth/domain/CurrentUser.java
- src/main/java/com/backend/arthere/auth/domain/HttpCookieOAuth2AuthorizationRequestRepository.java
- src/main/java/com/backend/arthere/auth/domain/UserPrincipal.java
- src/main/java/com/backend/arthere/auth/dto/GoogleOAuth2UserInfo.java
- src/main/java/com/backend/arthere/auth/dto/OAuth2Attributes.java
- src/main/java/com/backend/arthere/auth/dto/OAuth2UserInfo.java
- src/main/java/com/backend/arthere/auth/dto/request/TokenRequest.java
- src/main/java/com/backend/arthere/auth/dto/response/TokenResponse.java
- src/main/java/com/backend/arthere/auth/exception/InvalidRefreshTokenException.java
- src/main/java/com/backend/arthere/auth/exception/RefreshTokenNotFoundException.java
- src/main/java/com/backend/arthere/auth/handler/OAuth2LoginFailureHandler.java
- src/main/java/com/backend/arthere/auth/handler/OAuth2LoginSuccessHandler.java
- src/main/java/com/backend/arthere/auth/presentation/AuthController.java
- src/main/java/com/backend/arthere/auth/util/CookieUtils.java
- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/java/com/backend/arthere/global/config/WebMvcConfig.java
- src/main/resources/application.yml
Oauth2 구글 로그인 기능을 구현한다.
액세스 토큰 재발급, 로그아웃 기능을 구현한다.
프론트엔드 포트 번호를 3000으로 지정했습니다. (변경 가능)
> [feat] Oauth2 구글 로그인 기능 구현

- build.gradle
- src/main/java/com/backend/arthere/auth/application/AuthService.java
- src/main/java/com/backend/arthere/auth/dto/request/TokenRequest.java
- src/main/java/com/backend/arthere/auth/presentation/AuthController.java
- src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
- src/main/java/com/backend/arthere/global/error/ErrorResponse.java
- src/test/java/com/backend/arthere/auth/application/AuthServiceTest.java
- src/test/java/com/backend/arthere/auth/presentation/AuthControllerTest.java
- src/test/java/com/backend/arthere/auth/util/CookieUtilsTest.java
- src/test/java/com/backend/arthere/fixture/MemberFixtures.java
- src/test/java/com/backend/arthere/fixture/TokenFixtures.java
auth 컨트롤러, 서비스, 쿠키 유틸리티 테스트 구현
예외 처리 클래스 구현
auth와 관련된 클래스의 코드 수정을 진행했습니다.
> [test] auth 테스트 코드를 구현한다.

- src/main/java/com/backend/arthere/ArtHereApplication.java
- src/main/java/com/backend/arthere/auth/jwt/JwtTokenProvider.java
- src/main/java/com/backend/arthere/auth/presentation/AuthController.java
- src/main/java/com/backend/arthere/global/config/JpaConfig.java
- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
- src/test/java/com/backend/arthere/auth/application/CustomUserDetailsServiceTest.java
- src/test/java/com/backend/arthere/auth/domain/TokenRepositoryTest.java
- src/test/java/com/backend/arthere/auth/domain/TokenTest.java
- src/test/java/com/backend/arthere/auth/jwt/JwtTokenAuthenticationFilterTest.java
- src/test/java/com/backend/arthere/auth/jwt/JwtTokenProviderTest.java
- src/test/java/com/backend/arthere/auth/presentation/AuthControllerTest.java
jwt에 관련된 테스트를 구현했습니다.
애플리케이션 클래스에 명시한 JpaAuditing을 설정 파일로 분리해서
필요한 테스트 클래스에서 import할 수 있도록 했습니다.
일단 로그인 관련 테스트는 여기서 마무리하겠습니다~!
> [test] jwt 테스트를 구현한다.

- src/main/java/com/backend/arthere/global/config/WebMvcConfig.java
- src/main/resources/application.yml
> [feat] 프론트엔드 포트 번호 변경

- build.gradle
- src/docs/asciidoc/auth.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/com/backend/arthere/auth/presentation/AuthController.java
- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/java/com/backend/arthere/global/error/ErrorResponse.java
- src/main/resources/static/docs/auth.html
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/auth/presentation/AuthControllerTest.java
- src/test/java/com/backend/arthere/global/ControllerTest.java
- src/test/java/com/backend/arthere/global/RestDocsConfig.java
- 스프링 rest docs 설정 세팅
- asciidoc 문서 작성, html 파일 생성
- auth controller test에 rest docs 적용
> [docs] 스프링 rest docs를 구현한다.

- src/main/java/com/backend/arthere/auth/dto/response/LoginResponse.java
- src/main/java/com/backend/arthere/auth/handler/OAuth2LoginSuccessHandler.java
- src/main/resources/application.yml
> [feat] 로그인 로직 변경

- build.gradle
- src/docs/asciidoc/image.adoc
- src/docs/asciidoc/index.adoc
- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/java/com/backend/arthere/image/application/ImageService.java
- src/main/java/com/backend/arthere/image/dto/ImageResponse.java
- src/main/java/com/backend/arthere/image/dto/ImageUploadResponse.java
- src/main/java/com/backend/arthere/image/presentation/ImageController.java
- src/main/java/com/backend/arthere/image/util/PresignedURLUtils.java
- src/main/resources/application-local.yml
- src/main/resources/application.yml
- src/test/java/com/backend/arthere/image/application/ImageServiceTest.java
- src/test/java/com/backend/arthere/image/presentation/ImageControllerTest.java
- 이미지 공유, 업로드, 삭제 presigned URL 생성
- 이미지 공유, 업로드 삭제 presigned URL 요청 api
> [feat] s3 이미지 공유, 업로드, 삭제 구현

- src/main/resources/static/docs/image.html
- src/main/resources/static/docs/index.html
> [feat] image.html 추가

- build.gradle
- src/main/java/com/backend/arthere/global/config/QueryDslConfig.java
> [chore] QueryDSL 적용한다.

- src/main/java/com/backend/arthere/arts/application/ArtsService.java
- src/main/java/com/backend/arthere/arts/domain/Arts.java
- src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepository.java
- src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepositoryImpl.java
- src/main/java/com/backend/arthere/arts/dto/ArtImageByLocationResponse.java
- src/main/java/com/backend/arthere/arts/dto/LocationRangeResponse.java
- src/main/java/com/backend/arthere/arts/presentation/ArtsController.java
- src/main/java/com/backend/arthere/arts/util/LocationUtils.java
- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/test/java/com/backend/arthere/arts/util/LocationUtilsTest.java
- 요청한 위치값 반경 50m 내에 예술작품 데이터 반환 API 구현
- 반경내 좌표값 계산 메서드 구현
- 테스트 코드, API문서 미구현
> [feat] map image API

- src/main/java/com/backend/arthere/arts/domain/Address.java
- src/main/java/com/backend/arthere/arts/domain/Arts.java
- src/main/java/com/backend/arthere/arts/domain/Category.java
- src/main/java/com/backend/arthere/arts/domain/Location.java
- src/main/java/com/backend/arthere/arts/exception/InvalidCategoryException.java
- src/main/java/com/backend/arthere/details/application/DetailsService.java
- src/main/java/com/backend/arthere/details/domain/Details.java
- src/main/java/com/backend/arthere/details/domain/DetailsRepository.java
- src/main/java/com/backend/arthere/details/domain/ExhibitionPeriod.java
- src/main/java/com/backend/arthere/details/dto/request/ArtRequest.java
- src/main/java/com/backend/arthere/details/dto/response/ArtMapResponse.java
- src/main/java/com/backend/arthere/details/dto/response/ArtResponse.java
- src/main/java/com/backend/arthere/details/dto/response/ArtSaveResponse.java
- src/main/java/com/backend/arthere/details/exception/DetailsNotFoundException.java
- src/main/java/com/backend/arthere/details/presentation/DetailsController.java
- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
- 작품 조회/저장 API 구현
커밋 수가 많아서 테스트는 따로 pr하겠습니다
> [feat] 작품 조회/저장 API 구현

- src/docs/asciidoc/arts.adoc
- src/main/resources/static/docs/arts.html
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/arts/application/ArtsServiceTest.java
- src/test/java/com/backend/arthere/arts/domain/ArtsRepositoryTest.java
- src/test/java/com/backend/arthere/arts/presentation/ArtsControllerTest.java
- controller, service, repository test 추가
- api 문서 작성
> [test]/map image API 테스트 코드 추가, API 문서 작성

- src/docs/asciidoc/details.adoc
- src/main/java/com/backend/arthere/arts/domain/Arts.java
- src/main/java/com/backend/arthere/details/application/DetailsService.java
- src/main/java/com/backend/arthere/details/domain/Details.java
- src/main/java/com/backend/arthere/details/domain/DetailsRepository.java
- src/main/java/com/backend/arthere/details/presentation/DetailsController.java
- src/main/resources/static/docs/details.html
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/details/application/DetailsServiceTest.java
- src/test/java/com/backend/arthere/details/domain/DetailsRepositoryTest.java
- src/test/java/com/backend/arthere/details/domain/DetailsTest.java
- src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
- src/test/java/com/backend/arthere/fixture/EntireArtsFixtures.java
- 작품 수정/삭제 API 구현
- 테스트 코드 작성
- API 문서 작성
> [feat] 작품 수정/삭제 API 구현, 테스트 코드 작성

- src/main/java/com/backend/arthere/global/config/WebMvcConfig.java
> [fix] 프론트엔드 도메인 CORS 설정 추가

- src/main/java/com/backend/arthere/arts/application/ArtsService.java
- src/main/java/com/backend/arthere/global/config/AdminS3Config.java
- src/main/java/com/backend/arthere/image/application/ImageService.java
- src/main/java/com/backend/arthere/image/util/PresignedURLUtils.java
- src/test/java/com/backend/arthere/arts/application/ArtsServiceTest.java
- src/test/java/com/backend/arthere/image/application/ImageServiceTest.java
- S3 mock 서버 적용을 위한 S3 client 분리
- 변경으로 인한 테스트 코드 수정
> [Feature] s3 image 리팩토링

- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/java/com/backend/arthere/global/config/WebMvcConfig.java
http 메소드를 명시한다.
preflight 요청을 허용한다.
> [refactor] preflight 요청 허용

- src/docs/asciidoc/arts.adoc
- src/main/java/com/backend/arthere/arts/application/ArtsService.java
- src/main/java/com/backend/arthere/arts/dto/ArtImageByLocationRequest.java
- src/main/java/com/backend/arthere/arts/presentation/ArtsController.java
- src/main/java/com/backend/arthere/arts/util/LocationUtils.java
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/arts/application/ArtsServiceTest.java
- src/test/java/com/backend/arthere/arts/presentation/ArtsControllerTest.java
- src/test/java/com/backend/arthere/arts/util/LocationUtilsTest.java
- 유효성 검사를 위한 파라미터를 dto로 생성해 받아오는 데이터 검증
- 지도 반경 변경 가능하게 바꿈
- 요청 데이터가 없을때 빈 데이터 반환으로 바꿈
- 테스트 케이스 수정
> [feat] 지도 이미지 API 리팩토링

- src/main/java/com/backend/arthere/arts/domain/Address.java
- src/main/java/com/backend/arthere/arts/domain/Arts.java
- src/main/java/com/backend/arthere/arts/domain/Category.java
- src/main/java/com/backend/arthere/details/domain/Details.java
- src/main/java/com/backend/arthere/details/domain/ExhibitionPeriod.java
- src/main/java/com/backend/arthere/details/dto/request/ArtRequest.java
- src/main/java/com/backend/arthere/details/dto/response/ArtResponse.java
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/arts/domain/ArtsRepositoryTest.java
- src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
- src/test/java/com/backend/arthere/fixture/ArtsFixtures.java
- src/test/java/com/backend/arthere/fixture/DetailsFixtures.java
- 구주소 삭제
- 카테고리 종류 변경
- 작가 이름 null로 변경
> [refactor] 작품 관련 변경사항을 적용한다.

- src/docs/asciidoc/details.adoc
- src/main/java/com/backend/arthere/arts/domain/Arts.java
- src/main/java/com/backend/arthere/details/domain/DetailsCustomRepositoryImpl.java
- src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/details/domain/DetailsRepositoryTest.java
- src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
- 최신순, 작품명순 정렬 구현
- 커버링 인덱스 적용
- 테스트 코드 작성
- api 문서 작성
> [feat] 관리자 작품 조회 필터 기능을 구현한다. 

- src/main/java/com/backend/arthere/arts/application/ArtsService.java
- src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepository.java
- src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepositoryImpl.java
- src/main/java/com/backend/arthere/arts/dto/request/ArtImageByAddressRequest.java
- src/main/java/com/backend/arthere/arts/dto/request/ArtImageByArtNameRequest.java
- src/main/java/com/backend/arthere/arts/dto/request/ArtImageByLocationRequest.java
- src/main/java/com/backend/arthere/arts/dto/request/ArtImageByRevisionDateRequest.java
- src/main/java/com/backend/arthere/arts/dto/response/ArtImageByAddressResponse.java
- src/main/java/com/backend/arthere/arts/dto/response/ArtImageByArtNameResponse.java
- src/main/java/com/backend/arthere/arts/dto/response/ArtImageByLocationResponse.java
- src/main/java/com/backend/arthere/arts/dto/response/ArtImageByRevisionDateResponse.java
- src/main/java/com/backend/arthere/arts/dto/response/ArtImageResponse.java
- src/main/java/com/backend/arthere/arts/dto/response/LocationRangeResponse.java
- src/main/java/com/backend/arthere/arts/presentation/ArtsController.java
- src/main/java/com/backend/arthere/arts/util/LocationUtils.java
- src/test/java/com/backend/arthere/arts/application/ArtsServiceTest.java
- src/test/java/com/backend/arthere/arts/domain/ArtsRepositoryTest.java
- src/test/java/com/backend/arthere/arts/presentation/ArtsControllerTest.java
- src/test/java/com/backend/arthere/arts/util/LocationUtilsTest.java
- src/test/java/com/backend/arthere/fixture/ArtsFixtures.java
- 파일 구조 변경
- 반경 더 넓게 입력할 수 있도록 변경
> [refactor] 파일 구조 변경, 반경 최대 50000으로 변경

- src/docs/asciidoc/arts.adoc
- src/main/java/com/backend/arthere/arts/domain/ArtsCustomRepositoryImpl.java
- src/main/java/com/backend/arthere/arts/dto/request/ArtImageByAddressRequest.java
- src/main/java/com/backend/arthere/arts/dto/request/ArtImageByArtNameRequest.java
- src/main/java/com/backend/arthere/arts/dto/request/ArtImageByRevisionDateRequest.java
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/arts/presentation/ArtsControllerTest.java
- 메인 화면 이미지, 검색 이미지 카테고리 요청 기능 추가
- 관련 test 코드 추가
> [feate] 카테고리 분류 기능 추가

- src/docs/asciidoc/image.adoc
- src/main/java/com/backend/arthere/global/config/AdminS3Config.java
- src/main/java/com/backend/arthere/global/config/UserS3Config.java
- src/main/java/com/backend/arthere/image/application/ImageService.java
- src/main/java/com/backend/arthere/image/presentation/ImageController.java
- src/main/resources/application.yml
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/image/application/ImageServiceTest.java
- src/test/java/com/backend/arthere/image/presentation/ImageControllerTest.java
- 게시물 이미지 업로드할 s3 설정
- 게시물 이미지 업로드, 삭제 구현
- 테스트 작성
- api 문서 수정
> [기능]  s3 게시물 이미지 업로드, 삭제 구현

- src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
관리자가 작품을 저장할 때 올바르지 않은 날짜 형식 입력 시 오류 처리
> [feat] 데이터 형식이 올바르지 않을 때 에러 처리

- src/docs/asciidoc/auth.adoc
- src/docs/asciidoc/comment.adoc
- src/docs/asciidoc/member.adoc
- src/main/java/com/backend/arthere/comment/application/CommentService.java
- src/main/java/com/backend/arthere/comment/domain/CommentRepository.java
- src/main/java/com/backend/arthere/comment/dto/response/CommentPageResponse.java
- src/main/java/com/backend/arthere/comment/dto/response/CommentResponse.java
- src/main/java/com/backend/arthere/comment/presentation/CommentController.java
- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/java/com/backend/arthere/member/domain/Member.java
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/comment/application/CommentServiceTest.java
- src/test/java/com/backend/arthere/comment/domain/CommentRepositoryTest.java
- src/test/java/com/backend/arthere/comment/presentation/CommentControllerTest.java
- src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
- src/test/java/com/backend/arthere/dislike/presentation/DislikeControllerTest.java
- src/test/java/com/backend/arthere/fixture/CommentFixtures.java
- src/test/java/com/backend/arthere/global/ControllerTest.java
- src/test/java/com/backend/arthere/like/presentation/LikeControllerTest.java
- src/test/java/com/backend/arthere/member/domain/MemberTest.java
- 댓글 조회, 삭제 기능 구현
- 테스트 코드 작성
- api 문서 작성
> [feat] 댓글 조회, 삭제 기능 구현

- src/main/java/com/backend/arthere/details/application/DetailsService.java
- src/main/java/com/backend/arthere/details/domain/Details.java
- src/main/java/com/backend/arthere/details/dto/response/ArtResponse.java
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/details/application/DetailsServiceTest.java
- src/test/java/com/backend/arthere/details/domain/DetailsRepositoryTest.java
- src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
- 작품 세부 조회시 위도, 경도 데이터 추가 반환
- 테스트 코드, api 문서 수정
- arts 영속성 전이 제거 -> arts가 여러 곳에서 참조되기 때문에 
> [refactor] 작품 세부 조회에 위도, 경도 데이터 추가

- src/main/java/com/backend/arthere/arts/domain/Arts.java
- src/main/java/com/backend/arthere/arts/exception/ArtsNotFoundException.java
- src/main/java/com/backend/arthere/satisfactions/application/SatisfactionsService.java
- src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionType.java
- src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepository.java
- src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepositoryImpl.java
- src/main/java/com/backend/arthere/satisfactions/domain/StarRatings.java
- src/main/java/com/backend/arthere/satisfactions/dto/request/CreateSatisfactionsRequest.java
- src/main/java/com/backend/arthere/satisfactions/dto/response/GetTotalToDetailsResponse.java
- src/main/java/com/backend/arthere/satisfactions/dto/response/SatisfactionsListResponse.java
- src/main/java/com/backend/arthere/satisfactions/dto/response/SatisfactionsResponse.java
- src/main/java/com/backend/arthere/satisfactions/presentation/SatisfactionsController.java
- src/main/java/com/backend/arthere/starRatings/domain/StarRatings.java
- src/main/java/com/backend/arthere/starRatings/domain/StarRatingsCustomRepository.java
- src/main/java/com/backend/arthere/starRatings/domain/StarRatingsCustomRepositoryImpl.java
- src/main/java/com/backend/arthere/starRatings/domain/StarRatingsRepository.java
> feat: 만족도 관련 api 

- src/main/java/com/backend/arthere/auth/domain/HttpCookieOAuth2AuthorizationRequestRepository.java
- src/main/java/com/backend/arthere/auth/handler/OAuth2LoginSuccessHandler.java
- src/main/java/com/backend/arthere/global/error/ControllerAdvice.java
- src/main/java/com/backend/arthere/member/domain/Role.java
- src/main/java/com/backend/arthere/member/exception/InvalidRoleException.java
- src/main/resources/application-local.yml
- 구글 로그인 완료 후 사용자의 Role 정보를 반환한다.
> [feat] 로그인 완료 후 사용자의 Role 반환

- src/main/java/com/backend/arthere/arts/domain/Arts.java
- src/main/java/com/backend/arthere/member/domain/Member.java
- src/main/java/com/backend/arthere/satisfactions/application/SatisfactionsService.java
- src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepository.java
- src/main/java/com/backend/arthere/satisfactions/domain/SatisfactionsCustomRepositoryImpl.java
- src/main/java/com/backend/arthere/satisfactions/dto/request/AddSatisfactionsRequest.java
- src/main/java/com/backend/arthere/satisfactions/dto/request/CreateSatisfactionsRequest.java
- src/main/java/com/backend/arthere/satisfactions/presentation/SatisfactionsController.java
- src/main/java/com/backend/arthere/starRatings/domain/StarRatings.java
- src/main/java/com/backend/arthere/starRatings/domain/StarRatingsCustomRepository.java
- src/main/java/com/backend/arthere/starRatings/domain/StarRatingsCustomRepositoryImpl.java
> [Feat] 만족도 api

- src/docs/asciidoc/arts.adoc
- src/main/java/com/backend/arthere/post/application/PostService.java
- src/main/java/com/backend/arthere/post/domain/PostRepository.java
- src/main/java/com/backend/arthere/post/dto/response/PostResponse.java
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/fixture/PostFixtures.java
- src/test/java/com/backend/arthere/post/presentation/PostControllerTest.java
- 게시물 세부 조회시 작성자 여부 데이터 추가
- 좋아요, 싫어요 count 쿼리에 Modifying 어노테이션 옵션 추가
- 관련 테스트 코드 수정
- api 문서 수정
> [refactor] 게시물 세부 조회 리팩토링, 좋아요 싫어요 count 쿼리 수정

- src/main/java/com/backend/arthere/global/config/SecurityConfig.java
- src/main/java/com/backend/arthere/post/application/PostService.java
- src/main/java/com/backend/arthere/post/domain/PostCustomRepository.java
- src/main/java/com/backend/arthere/post/domain/PostCustomRepositoryImpl.java
- src/main/java/com/backend/arthere/post/domain/PostRepository.java
- src/main/java/com/backend/arthere/post/dto/response/PostInfoResponse.java
- src/main/java/com/backend/arthere/post/dto/response/PostsResponse.java
- src/main/java/com/backend/arthere/post/presentation/PostController.java
> [feat] post 데이터 반환 API

- src/main/java/com/backend/arthere/post/application/PostService.java
- src/main/java/com/backend/arthere/post/dto/resquest/CreatePostsRequest.java
- src/main/java/com/backend/arthere/post/presentation/PostController.java
> [feat] post 저장 api

- src/main/java/com/backend/arthere/post/application/PostService.java
- src/main/java/com/backend/arthere/post/domain/Post.java
- src/main/java/com/backend/arthere/post/dto/request/AddPostsRequest.java
- src/main/java/com/backend/arthere/post/dto/request/CreatePostsRequest.java
- src/main/java/com/backend/arthere/post/presentation/PostController.java
> [Feat] post 수정 API 구현

- src/main/java/com/backend/arthere/post/application/PostService.java
- src/main/java/com/backend/arthere/post/presentation/PostController.java
> [feat] post 삭제 API 구현

- src/main/java/com/backend/arthere/details/application/DetailsService.java
- src/main/java/com/backend/arthere/details/dto/response/ArtResponse.java
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
> [Feat] 이미지 URL 반환 데이터 추가

- src/main/java/com/backend/arthere/details/dto/response/ArtResponse.java
- src/main/resources/static/docs/index.html
- src/test/java/com/backend/arthere/details/presentation/DetailsControllerTest.java
> [refactor] 작품 이름 반환 추가
